[".oh-my-zsh"]
type = "git-repo"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
ref = "master"
refreshPeriod = "168h"

# [".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
# type = "git-repo"
# url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
# refreshPeriod = "168h"
#
# [".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
# type = "git-repo"
# url = "https://github.com/zsh-users/zsh-autosuggestions.git"
# refreshPeriod = "168h"
#
# [".oh-my-zsh/custom/themes/powerlevel10k"]
# type = "git-repo"
# url = "https://github.com/romkatv/powerlevel10k.git"

[".zsh/pure"]
type = "git-repo"
url = "https://github.com/sindresorhus/pure.git"
refreshPeriod = "168h"

[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"

[".vim/autoload/plug.vim"]
type = "file"
url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
refreshPeriod = "168h"

[".config/nvim"]
type = "git-repo"
url = "https://github.com/AstroNvim/template.git"
refreshPeriod = "168h"

[".config/kitty/kitty-themes"]
type = "git-repo"
url = "https://github.com/dexpota/kitty-themes.git"
refreshPeriod = "168h"


[".config/polybar/polybar-scripts"]
type = "git-repo"
url = "https://github.com/polybar/polybar-scripts"
refreshPeriod = "168h"

[".config/polybar/catppuccin"]
type = "git-repo"
url = "https://github.com/catppuccin/polybar"
refreshPeriod = "168h"

["antigen"]
type = "git-repo"
url = "https://github.com/zsh-users/antigen.git"
refreshPeriod = "168h"

[".local/share/autojump"]
type = "git-repo"
url = "https://github.com/wting/autojump.git"
refreshPeriod = "168h"
