[".oh-my-zsh"]
type = "git"
url = "https://github.com/ohmyzsh/ohmyzsh.git"
refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "git"
url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh--autosuggestions"]
type = "git"
url = "https://github.com/zsh-users/zsh-autosuggestions.git"
refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
type = "git"
url = "https://github.com/romkatv/powerlevel10k.git"

[".zsh/pure"]
type = "git"
url = "https://github.com/sindresorhus/pure.git"
refreshPeriod = "168h"
